name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build_linux:
    strategy:
      matrix:
        docker_image: ['realnc/qtads-build:linux-x86', 'realnc/qtads-build:linux-x64']

    runs-on: ubuntu-latest
    container: ${{ matrix.docker_image }}

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        qmake
        make appimage

  build_macOS:
    runs-on: macos-10.15

    steps:
    - name: Install deps
      run: |
        brew install \
          fluidsynth \
          libsndfile \
          libvorbis \
          mpg123 \
          pkg-config \
          qt5 \
          sdl2
        brew link qt5 --force

    - uses: actions/checkout@v2
    - name: Build
      run: |
        qmake qtads.pro
        make -j`sysctl -n hw.ncpu`
